version: "3.8"
networks:
  crud-network:
    driver: bridge
services:
  reactapp:
    build: ./Frontend/frontend/.
    container_name: react_vite_app
    ports:
      - '3000:3000'
    restart: always
    networks:
      - crud-network
  djangoapp:
    build: ./backend/.
    container_name: djangoapp
    ports:
      - '8000:8000'
    restart: always
    networks:
      - crud-network
